#!/usr/bin/env bash

set -eo pipefail

hxnormalize -x -d -l 10000000 -s -L "$1"	\
| hxselect -i -c 'div.article__body'	\
| hxselect -i 'div[data-type="text"],div[data-type="quote"]'	\
| hxremove -i 'div.article__quote-bg,strong'	\
| sed -E -e 's|</?[[:alpha:]][^>]*>||g' -e 's/^[[:blank:]]+//' -e 's/\.\.\./…/g'	\
| cat -s	\
| hxunent
